name: Frontend CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests (Jest)
        run: npm run test -- --watchAll=false

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out frontend
        uses: actions/checkout@v3

      - name: Run e2e tests
        run: |
          docker compose -f docker-compose.e2e.yml up --build --abort-on-container-exit --exit-code-from cypress
