name: Frontend CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests (Jest)
        run: npm run test -- --watchAll=false

      # If you decide to run E2E tests locally (without staging):
      - name: Build for E2E
        run: npm run build

      - name: Start local server
        run: npx serve -s build -l 3000 &
        # Give it a second to start
      - run: npx wait-on http://localhost:3000

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out frontend
        uses: actions/checkout@v3

      # If you're pulling a pre-built image, skip the build steps.
      # Otherwise, if you're building from Dockerfile.backend,
      # the next step does "docker-compose build" as part of up.

      - name: Docker Compose Up
        run: |
          docker compose -f docker-compose.e2e.yml up --build --abort-on-container-exit --exit-code-from cypress
